CREATE TABLE `data_batas_desa` (
    `id` int(11) NOT NULL auto_increment,
    `id_desa` VARCHAR(10) DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `kab_kot` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `area` TEXT DEFAULT NULL,
    `perimeter` TEXT DEFAULT NULL,
    `hectares` TEXT DEFAULT NULL,
    `ukuran_kot` TEXT DEFAULT NULL,
    `pemusatan` TEXT DEFAULT NULL,
    `jumplah_pen` TEXT DEFAULT NULL,
    `provno` VARCHAR(10) DEFAULT NULL,
    `kabkotno` VARCHAR(10) DEFAULT NULL,
    `kecno` VARCHAR(10) DEFAULT NULL,
    `desano` VARCHAR(10) DEFAULT NULL,
    `id2012` TEXT DEFAULT NULL,
    `polygon` LONGTEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    PRIMARY KEY  (id)
);

CREATE TABLE `data_batas_kecamatan` (
    `id` int(11) NOT NULL auto_increment,
    `provno` VARCHAR(10) DEFAULT NULL,
    `kabkotno` VARCHAR(10) DEFAULT NULL,
    `kecno` VARCHAR(10) DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `id2012` TEXT DEFAULT NULL,
    `polygon` LONGTEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    PRIMARY KEY  (id)
);

CREATE TABLE `data_p3ke` (
    `id` int(11) NOT NULL auto_increment,
    `id_p3ke` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `kode_kemendagri` TEXT DEFAULT NULL,
    `jenis_desil` TINYINT(1) DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `kepala_keluarga` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `padan_dukcapil` VARCHAR(30) DEFAULT NULL,
    `jenis_kelamin` VARCHAR(30) DEFAULT NULL,
    `tanggal_lahir` datetime DEFAULT NULL,
    `pekerjaan` TEXT DEFAULT NULL,
    `pendidikan` TEXT DEFAULT NULL,
    `rumah` TEXT DEFAULT NULL,
    `punya_tabungan` VARCHAR(30) DEFAULT NULL,
    `jenis_atap` TEXT DEFAULT NULL,
    `jenis_dinding` TEXT DEFAULT NULL,
    `jenis_lantai` TEXT DEFAULT NULL,
    `sumber_penerangan` TEXT DEFAULT NULL,
    `bahan_bakar_memasak` TEXT DEFAULT NULL,
    `sumber_air_minum` TEXT DEFAULT NULL,
    `fasilitas_bab` TEXT DEFAULT NULL,
    `penerima_bpnt` VARCHAR(30) DEFAULT NULL,
    `penerima_bpum` VARCHAR(30) DEFAULT NULL,
    `penerima_bst` VARCHAR(30) DEFAULT NULL,
    `penerima_pkh` VARCHAR(30) DEFAULT NULL,
    `penerima_sembako` VARCHAR(30) DEFAULT NULL,
    `resiko_stunting` VARCHAR(30) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    `tahun_anggaran` year(4) DEFAULT NULL,
    PRIMARY KEY  (id)
);

CREATE TABLE `data_p3ke_anggota_keluarga` (
    `id` int(11) NOT NULL auto_increment,
    `id_p3ke` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `kode_kemendagri` TEXT DEFAULT NULL,
    `jenis_desil` TINYINT(1) DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `id_individu` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `padan_dukcapil` VARCHAR(30) DEFAULT NULL,
    `jenis_kelamin` VARCHAR(30) DEFAULT NULL,
    `hubungan_keluarga` VARCHAR(30) DEFAULT NULL,
    `tanggal_lahir` datetime DEFAULT NULL,
    `status_kawin` VARCHAR(30) DEFAULT NULL,
    `pekerjaan` TEXT DEFAULT NULL,
    `pendidikan` TEXT DEFAULT NULL,
    `usia_dibawah_7` VARCHAR(30) DEFAULT NULL,
    `usia_7_12` VARCHAR(30) DEFAULT NULL,
    `usia_13_15` VARCHAR(30) DEFAULT NULL,
    `usia_16_18` VARCHAR(30) DEFAULT NULL,
    `usia_19_21` VARCHAR(30) DEFAULT NULL,
    `usia_22_59` VARCHAR(30) DEFAULT NULL,
    `usia_60_keatas` VARCHAR(30) DEFAULT NULL,
    `penerima_bpnt` VARCHAR(30) DEFAULT NULL,
    `penerima_bpum` VARCHAR(30) DEFAULT NULL,
    `penerima_bst` VARCHAR(30) DEFAULT NULL,
    `penerima_pkh` VARCHAR(30) DEFAULT NULL,
    `penerima_sembako` VARCHAR(30) DEFAULT NULL,
    `resiko_stunting` VARCHAR(30) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    `tahun_anggaran` year(4) DEFAULT NULL,
    PRIMARY KEY  (id)
);

CREATE TABLE `data_stunting` (
    `id` int(11) NOT NULL auto_increment,
    `nik` TEXT DEFAULT NULL,
    `no_kk` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `jenis_kelamin` VARCHAR(2) DEFAULT NULL,
    `tanggal_lahir` TEXT DEFAULT NULL,
    `bb_lahir` int(11) DEFAULT NULL,
    `tb_lahir` int(11) DEFAULT NULL,
    `nama_ortu` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `puskesmas` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `posyandu` TEXT DEFAULT NULL,
    `rt` int(11) DEFAULT NULL,
    `rw` int(11) DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `usia_saat_ukur` TEXT DEFAULT NULL,
    `tanggal_pengukuran` TEXT DEFAULT NULL,
    `berat` int(11) DEFAULT NULL,
    `tinggi` int(11) DEFAULT NULL,
    `lingkar_lengan_atas` TEXT DEFAULT NULL,
    `bb_per_u` TEXT DEFAULT NULL,
    `zs_bb_per_u` int(11) DEFAULT NULL,
    `tb_per_u` TEXT DEFAULT NULL,
    `zs_tb_per_u` int(11) DEFAULT NULL,
    `bb_per_tb` TEXT DEFAULT NULL,
    `zs_bb_per_tb` int(11) DEFAULT NULL,
    `naik_berat_badan` VARCHAR(4) DEFAULT NULL,
    `pmt_diterima_per_kg` VARCHAR(100) DEFAULT NULL,
    `jml_vit_a` VARCHAR(100) DEFAULT NULL,
    `kpsp` VARCHAR(100) DEFAULT NULL,
    `kia` VARCHAR(100) DEFAULT NULL,
    `jkn_bps`  TEXT DEFAULT NULL,   
    `air_bersih`  TEXT DEFAULT NULL,    
    `kecacingan`  TEXT DEFAULT NULL,
    `jamban_sehat`  TEXT DEFAULT NULL,  
    `imunisasi`  TEXT DEFAULT NULL, 
    `keluarga_merokok`  TEXT DEFAULT NULL,  
    `riwayat_ibu_hamil`  TEXT DEFAULT NULL, 
    `penyakit_penyerta`  TEXT DEFAULT NULL,
    `tanggal_tindakan` datetime DEFAULT NULL,
    `jenis_tindakan`  TEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    `tahun_anggaran` year(4) DEFAULT NULL,
    PRIMARY KEY  (id)
);

CREATE TABLE `data_tbc` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `kdwil` VARCHAR(20) DEFAULT NULL,  
    `tanggal_register` TEXT DEFAULT NULL,
    `no_reg_fasyankes` TEXT DEFAULT NULL,
    `no_reg_kabkot` TEXT DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `umur` INT(11) DEFAULT NULL,
    `jenis_kelamin` VARCHAR(4) DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `pindahan_dari_fasyankes` TEXT DEFAULT NULL,
    `tindak_lanjut` TEXT DEFAULT NULL,
    `tanggal_mulai_pengobatan` TEXT DEFAULT NULL,
    `hasil_akhir_pengobatan` TEXT DEFAULT NULL,
    `status_pengobatan` TEXT DEFAULT NULL,
    `keterangan` TEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    `tahun_anggaran` year(4) DEFAULT NULL,
    PRIMARY KEY  (id)
);

CREATE TABLE `data_rtlh` (
    `id` int(11) NOT NULL auto_increment,
    `nik` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `rw` VARCHAR(5) DEFAULT NULL,
    `rt` VARCHAR(5) DEFAULT NULL,
    `nilai_bantuan` double DEFAULT NULL,
    `lpj` TEXT DEFAULT NULL,
    `tgl_lpj` TEXT DEFAULT NULL,
    `sumber_dana` TEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    `tahun_anggaran` year(4) DEFAULT NULL,
    PRIMARY KEY  (id)
);

CREATE TABLE `data_dtks_satset` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `desa` TEXT DEFAULT NULL,
    `desa_kelurahan` TEXT DEFAULT NULL,
    `id_kec` VARCHAR(30) DEFAULT NULL,
    `id_desa` VARCHAR(30) DEFAULT NULL,
    `Alamat` TEXT DEFAULT NULL,
    `BLT` TEXT DEFAULT NULL,
    `BLT_BBM` TEXT DEFAULT NULL,
    `BNPT_PPKM` TEXT DEFAULT NULL,
    `BPNT` TEXT DEFAULT NULL,
    `BST` TEXT DEFAULT NULL,
    `FIRST_SK` TEXT DEFAULT NULL,
    `NIK` TEXT DEFAULT NULL,
    `NOKK` TEXT DEFAULT NULL,
    `Nama` TEXT DEFAULT NULL,
    `PBI` TEXT DEFAULT NULL,
    `PKH` TEXT DEFAULT NULL,
    `RUTILAHU` TEXT DEFAULT NULL,
    `SEMBAKO_ADAPTIF` TEXT DEFAULT NULL,
    `checkBtnHamil` TEXT DEFAULT NULL,
    `checkBtnVerifMeninggal` TEXT DEFAULT NULL,
    `counter` TEXT DEFAULT NULL,
    `deleted_label` TEXT DEFAULT NULL,
    `idsemesta` TEXT DEFAULT NULL,
    `isAktifHamil` TEXT DEFAULT NULL,
    `is_btn_dapodik` TEXT DEFAULT NULL,
    `is_btn_hidupkan` TEXT DEFAULT NULL,
    `is_btn_padankan` TEXT DEFAULT NULL,
    `is_nonaktif` TEXT DEFAULT NULL,
    `keterangan_disabilitas` TEXT DEFAULT NULL,
    `keterangan_meninggal` TEXT DEFAULT NULL,
    `masih_hidup_label` TEXT DEFAULT NULL,
    `padankan_at` TEXT DEFAULT NULL,
    `periode_blt` TEXT DEFAULT NULL,
    `periode_blt_bbm` TEXT DEFAULT NULL,
    `periode_bpnt` TEXT DEFAULT NULL,
    `periode_bpnt_ppkm` TEXT DEFAULT NULL,
    `periode_bst` TEXT DEFAULT NULL,
    `periode_pbi` TEXT DEFAULT NULL,
    `periode_pkh` TEXT DEFAULT NULL,
    `periode_rutilahu` TEXT DEFAULT NULL,
    `periode_sembako_adaptif` TEXT DEFAULT NULL,
    `verifyid` TEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    `tahun_anggaran` year(4) DEFAULT NULL,
    PRIMARY KEY  (id),
    INDEX(`id_desa`)
);

CREATE TABLE `satset_data_unit` (
  `id` int(11) NOT NULL auto_increment,
  `id_setup_unit` int(11) DEFAULT NULL,
  `id_unit` int(11) DEFAULT NULL,
  `is_skpd` tinyint(4) DEFAULT NULL,
  `kode_skpd` varchar(50) DEFAULT NULL,
  `kunci_skpd` int(11) DEFAULT NULL,
  `nama_skpd` text DEFAULT NULL,
  `posisi` varchar(30) DEFAULT NULL,
  `status` varchar(30) DEFAULT NULL,
  `id_skpd` int(11) DEFAULT NULL,
  `bidur_1` smallint(6) DEFAULT NULL,
  `bidur_2` smallint(6) DEFAULT NULL,
  `bidur_3` smallint(6) DEFAULT NULL,
  `idinduk` int(11) DEFAULT NULL,
  `ispendapatan` tinyint(4) DEFAULT NULL,
  `isskpd` tinyint(4) DEFAULT NULL,
  `kode_skpd_1` varchar(10) DEFAULT NULL,
  `kode_skpd_2` varchar(10) DEFAULT NULL,
  `kodeunit` varchar(30) DEFAULT NULL,
  `komisi` int(11) DEFAULT NULL,
  `namabendahara` text,
  `namakepala` text DEFAULT NULL,
  `namaunit` text DEFAULT NULL,
  `nipbendahara` varchar(30) DEFAULT NULL,
  `nipkepala` varchar(30) DEFAULT NULL,
  `pangkatkepala` varchar(50) DEFAULT NULL,
  `setupunit` int(11) DEFAULT NULL,
  `statuskepala` varchar(20) DEFAULT NULL,
  `mapping` varchar(10) DEFAULT NULL,
  `id_kecamatan` int(11) DEFAULT NULL,
  `id_strategi` int(11) DEFAULT NULL,
  `is_dpa_khusus` tinyint(4) DEFAULT NULL,
  `is_ppkd` tinyint(4) DEFAULT NULL,
  `set_input` tinyint(4) DEFAULT NULL,
  `update_at` datetime DEFAULT NULL,
  `tahun_anggaran` year(4) DEFAULT NULL,
  `active` tinyint(4) NOT NULL DEFAULT '1',
  PRIMARY KEY  (id)
);

CREATE TABLE `data_dtsen_satset` (
    `id` int(11) NOT NULL auto_increment,
    `alamat` TEXT DEFAULT NULL,
    `desil_nasional` int(11) DEFAULT NULL,
    `id_keluarga` VARCHAR(225) DEFAULT NULL,
    `id_wilayah` VARCHAR(225) DEFAULT NULL,
    `nama_kepala_keluarga` TEXT DEFAULT NULL,
    `no_kk` VARCHAR(225) DEFAULT NULL,
    `peringkat_nasional` TEXT DEFAULT NULL,
    `kabupaten` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `kelurahan` TEXT DEFAULT NULL,
    `rt` VARCHAR(225) DEFAULT NULL,
    `rw` VARCHAR(225) DEFAULT NULL,
    `nik` VARCHAR(225) DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `percentile_nasional` TEXT DEFAULT NULL,
    `peringkat_kab_kota` TEXT DEFAULT NULL,
    `peringkat_provinsi` TEXT DEFAULT NULL,
    `status_nonaktif` VARCHAR(225) DEFAULT NULL,
    `padan_bulan_ini` tinyint(4) DEFAULT NULL,
    `active` tinyint(4) DEFAULT NULL,
    `update_at` DATETIME NOT NULL,
    PRIMARY KEY  (id),
    INDEX(`id_wilayah`),
    INDEX(`id_keluarga`),
    INDEX(`desil_nasional`),
    INDEX(`no_kk`),
    INDEX(`active`),
    INDEX(`nik`)
);

CREATE TABLE `data_dtsen_anggota_keluarga` (
    `id` int(11) NOT NULL auto_increment,
    `hub_kepala_keluarga` TEXT DEFAULT NULL,
    `id_keluarga` VARCHAR(225) DEFAULT NULL,
    `idsemesta` VARCHAR(225) DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `nik` VARCHAR(225) DEFAULT NULL,
    `no_kk` VARCHAR(225) DEFAULT NULL,
    `pekerjaan_utama` TEXT DEFAULT NULL,
    `button_status_dapodik` VARCHAR(225) DEFAULT NULL,
    `button_status_ortu` VARCHAR(225) DEFAULT NULL,
    `flag_aktif` tinyint(4) DEFAULT NULL,
    `keberadaan_anggota` TEXT DEFAULT NULL,
    `status_button_hamil` VARCHAR(225) DEFAULT NULL,
    `status_kedudukan_pekerjaan_utama` VARCHAR(225) DEFAULT NULL,
    `status_kpd` VARCHAR(225) DEFAULT NULL,
    `status_meninggal` VARCHAR(225) DEFAULT NULL,
    `alasan_tolak_meninggal` TEXT DEFAULT NULL,
    `tempat_lahir` VARCHAR(225) DEFAULT NULL,
    `tanggal_lahir` DATE DEFAULT NULL,
    `alamat_ktp` TEXT DEFAULT NULL,
    `rt` VARCHAR(20) DEFAULT NULL,
    `rw` VARCHAR(20) DEFAULT NULL,
    `jenis_kelamin` VARCHAR(50) DEFAULT NULL,
    `status_perkawinan` VARCHAR(100) DEFAULT NULL,
    `kartu_identitas` VARCHAR(100) DEFAULT NULL,
    `partisipasi_sekolah` VARCHAR(100) DEFAULT NULL,
    `jenjang_pendidikan` VARCHAR(100) DEFAULT NULL,
    `kelas_tertinggi` VARCHAR(100) DEFAULT NULL,
    `ijazah_tertinggi` VARCHAR(100) DEFAULT NULL,
    `status_kedudukan_pekerjaan_utama_detail` VARCHAR(225) DEFAULT NULL,
    `kepemilikan_izin_usaha` VARCHAR(225) DEFAULT NULL,
    `omset_usaha_utama` VARCHAR(225) DEFAULT NULL,
    `penggunaan_internet_usaha` VARCHAR(225) DEFAULT NULL,
    `penyakit_menahun` VARCHAR(225) DEFAULT NULL,
    `kondisi_gizi` VARCHAR(225) DEFAULT NULL,
    `id_ketrampilan` VARCHAR(225) DEFAULT NULL,
    `ketrampilan_sertifikat` VARCHAR(225) DEFAULT NULL,
    `group_ketrampilan` VARCHAR(225) DEFAULT NULL,
    `id_disabilitas` VARCHAR(225) DEFAULT NULL,
    `jenis_disabilitas` VARCHAR(225) DEFAULT NULL,
    `pendapatan_bulan_terakhir` VARCHAR(225) DEFAULT NULL,
    `jumlah_jenis_usaha` VARCHAR(50) DEFAULT NULL,
    `jumlah_pekerja_dibayar` VARCHAR(50) DEFAULT NULL,
    `jumlah_pekerja_tidak_dibayar` VARCHAR(50) DEFAULT NULL,
    `usaha_utama` VARCHAR(225) DEFAULT NULL,
    `ada_jenis_usaha` VARCHAR(10) DEFAULT NULL,
    `active` tinyint(4) DEFAULT NULL,
    `update_at` DATETIME NOT NULL,
    PRIMARY KEY  (id),
    INDEX(`id_keluarga`),
    INDEX(`no_kk`),
    INDEX(`nik`),
    INDEX(`active`),
    INDEX(`idsemesta`)
);

CREATE TABLE `data_dtsen_aset_keluarga` (
    `id` int(11) NOT NULL auto_increment,
    `id_keluarga` VARCHAR(225) DEFAULT NULL,
    `id_pelanggan` VARCHAR(225) DEFAULT NULL,
    `atap_terluas` VARCHAR(225) DEFAULT NULL,
    `bahan_bakar_utama` VARCHAR(225) DEFAULT NULL,
    `dinding_terluas` VARCHAR(225) DEFAULT NULL,
    `fasilitas_bab` VARCHAR(225) DEFAULT NULL,
    `jarak_sumberair_limbah` VARCHAR(225) DEFAULT NULL,
    `jenis_kloset` VARCHAR(225) DEFAULT NULL,
    `jml_babi` int(11) DEFAULT NULL,
    `jml_kambing_domba` int(11) DEFAULT NULL,
    `jml_keluarga` int(11) DEFAULT NULL,
    `jml_kerbau` int(11) DEFAULT NULL,
    `jml_kuda` int(11) DEFAULT NULL,
    `jml_sapi` int(11) DEFAULT NULL,
    `jumlah_anggota_keluarga` int(11) DEFAULT NULL,
    `lahan_tempat_lain` int(11) DEFAULT NULL,
    `lantai_terluas` TEXT DEFAULT NULL,
    `luas_sawah_kebun` VARCHAR(225) DEFAULT NULL,
    `pembuangan_tinja` VARCHAR(225) DEFAULT NULL,
    `rumah_tempat_lain` int(11) DEFAULT NULL,
    `status_penguasaan_bangunan` VARCHAR(225) DEFAULT NULL,
    `sumber_air_minum` VARCHAR(225) DEFAULT NULL,
    `sumber_penerangan` VARCHAR(225) DEFAULT NULL,
    `active` tinyint(4) DEFAULT NULL,
    `update_at` DATETIME NOT NULL,
    PRIMARY KEY  (id),
    INDEX(`id_keluarga`),
    INDEX(`id_pelanggan`),
    INDEX(`active`)
);

CREATE TABLE `data_dtsen_aset_bergerak` (
    `id` int(11) NOT NULL auto_increment,
    `id_keluarga` VARCHAR(225) DEFAULT NULL,
    `id_jenis_aset` tinyint(4) DEFAULT NULL,
    `jenis_aset` VARCHAR(225) DEFAULT NULL,
    `jumlah` int(11) DEFAULT NULL,
    `active` tinyint(4) DEFAULT NULL,
    `update_at` DATETIME NOT NULL,
    PRIMARY KEY  (id),
    INDEX(`id_keluarga`),
    INDEX(`id_jenis_aset`),
    INDEX(`active`)
);

CREATE TABLE `data_usulan_dtsen` (
    `id` int(11) NOT NULL auto_increment,
    `alamat` TEXT DEFAULT NULL,
    `id_desa_kel` VARCHAR(225) DEFAULT NULL,
    `no_kk` VARCHAR(225) DEFAULT NULL,
    `kabupaten` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `kelurahan` TEXT DEFAULT NULL,
    `rt` VARCHAR(30) DEFAULT NULL,
    `rw` VARCHAR(30) DEFAULT NULL,
    `provinsi` TEXT DEFAULT NULL,
    `status_data` TINYINT(1) NOT NULL COMMENT '0 = draft, 1 = menunggu persetujuan, 2 = disetujui, 3 = ditolak',
    `keterangan_verifikasi` TEXT,
    `active` tinyint(4) DEFAULT 1,
    `update_at` DATETIME NOT NULL,
    PRIMARY KEY  (id),
    INDEX(`status_data`),
    INDEX(`id_desa_kel`),
    INDEX(`no_kk`),
    INDEX(`active`)
);

CREATE TABLE `data_usulan_dtsen_anggota_keluarga` (
    `id` int(11) NOT NULL auto_increment,
    `id_keluarga` INT(11) NOT NULL,
    `is_kepala_keluarga` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0 = false, 1 = true',
    `hub_kepala_keluarga` TEXT DEFAULT NULL,
    `nama` TEXT DEFAULT NULL,
    `nik` VARCHAR(225) DEFAULT NULL,
    `pekerjaan_utama` TEXT DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `create_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX(`id_keluarga`),
    INDEX(`is_kepala_keluarga`),
    INDEX(`nik`),
    INDEX(`active`)
);

CREATE TABLE `data_rekap_jumlah_dtsen` (  
    `id` int(11) NOT NULL auto_increment,  
    `kdwil` VARCHAR(20) DEFAULT NULL,  
    `kelurahan` VARCHAR(255) DEFAULT NULL,  
    `wilayah` VARCHAR(255) DEFAULT NULL,  
    `keluarga_blm_desil` INT(11) DEFAULT NULL,  
    `anggota_blm_desil` INT(11) DEFAULT NULL,  
    `jumlah_keluarga` INT(11) DEFAULT NULL,  
    `jumlah_anggota_keluarga` INT(11) DEFAULT NULL,  
    `keluarga_desil_1` INT(11) DEFAULT NULL,  
    `anggota_desil_1` INT(11) DEFAULT NULL,  
    `keluarga_desil_2` INT(11) DEFAULT NULL,  
    `anggota_desil_2` INT(11) DEFAULT NULL,  
    `keluarga_desil_3` INT(11) DEFAULT NULL,  
    `anggota_desil_3` INT(11) DEFAULT NULL,  
    `keluarga_desil_4` INT(11) DEFAULT NULL,  
    `anggota_desil_4` INT(11) DEFAULT NULL,  
    `keluarga_desil_5` INT(11) DEFAULT NULL,  
    `anggota_desil_5` INT(11) DEFAULT NULL,  
    `keluarga_desil_6_10` INT(11) DEFAULT NULL,  
    `anggota_desil_6_10` INT(11) DEFAULT NULL,  
    `keluarga_tanpa_anggota` INT(11) DEFAULT NULL,  
    `anggota_meninggal` INT(11) DEFAULT NULL,  
    `update_at` DATETIME NOT NULL,  
    PRIMARY KEY (`id`),  
    INDEX(`kdwil`)  
);

CREATE TABLE `data_ats_satset` (
    `id` int(11) NOT NULL auto_increment,
    `nisn` VARCHAR(50) DEFAULT NULL,
    `nama` VARCHAR(255) DEFAULT NULL,
    `jenis_kelamin` VARCHAR(10) DEFAULT NULL,
    `usia` INT(11) DEFAULT NULL,
    `nama_ayah` VARCHAR(255) DEFAULT NULL,
    `nama_ibu` VARCHAR(255) DEFAULT NULL,
    `alamat` TEXT DEFAULT NULL,
    `npsn` VARCHAR(50) DEFAULT NULL,
    `nama_sekolah` VARCHAR(255) DEFAULT NULL,
    `tingkat_pendidikan` VARCHAR(255) DEFAULT NULL,
    `status` VARCHAR(50) DEFAULT NULL,
    `alasan_verifikasi` TEXT DEFAULT NULL,
    `alasan_lainnya` TEXT DEFAULT NULL,
    `keterangan` TEXT DEFAULT NULL,
    `provinsi` VARCHAR(100) DEFAULT NULL,
    `kab_kot` VARCHAR(100) DEFAULT NULL,
    `kecamatan` VARCHAR(100) DEFAULT NULL,
    `desa` VARCHAR(100) DEFAULT NULL,
    `kode` VARCHAR(100) DEFAULT NULL,
    `kdwil` VARCHAR(20) DEFAULT NULL,  
    `active` tinyint(4) DEFAULT 1,
    `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX(`nisn`),
    INDEX(`nama`),
    INDEX(`active`)
);

CREATE TABLE `data_aids` (
    `id` int(11) NOT NULL auto_increment,
    `provinsi` TEXT DEFAULT NULL,
    `kabkot` TEXT DEFAULT NULL,
    `kecamatan` TEXT DEFAULT NULL,
    `kode_upk` VARCHAR(20) DEFAULT NULL,
    `nama_upk` TEXT DEFAULT NULL,
    `id_pasien` VARCHAR(50) DEFAULT NULL,
    `warga_negara` VARCHAR(10) DEFAULT NULL,
    `nik` TEXT DEFAULT NULL,
    `nama_pasien` TEXT DEFAULT NULL,
    `tanggal_lahir` TEXT DEFAULT NULL,
    `jenis_kelamin` VARCHAR(30) DEFAULT NULL,
    `no_telp` TEXT DEFAULT NULL,
    `umur_terdiagnosis` VARCHAR(50) DEFAULT NULL,
    `kelompok_umur_terdiagnosis` VARCHAR(50) DEFAULT NULL,
    `kategori_umur_terdiagnosis` VARCHAR(50) DEFAULT NULL,
    `provinsi_pasien` TEXT DEFAULT NULL,
    `kabkot_pasien` TEXT DEFAULT NULL,
    `kecamatan_pasien` TEXT DEFAULT NULL,
    `desa_pasien` TEXT DEFAULT NULL,
    `alamat_pasien` TEXT DEFAULT NULL,
    `provinsi_domisili` TEXT DEFAULT NULL,
    `kabkot_domisili` TEXT DEFAULT NULL,
    `kecamatan_domisili` TEXT DEFAULT NULL,
    `desa_domisili` TEXT DEFAULT NULL,
    `alamat_domisili` TEXT DEFAULT NULL,
    `tanggal_register` TEXT DEFAULT NULL,
    `waktu_input_pertama` TEXT DEFAULT NULL,
    `no_rekam_medik` TEXT DEFAULT NULL,
    `kel_populasi_lsl` TINYINT(1) DEFAULT NULL,
    `konfirmasi_hiv_plus_tanggal_konfirmasi` TEXT DEFAULT NULL,
    `konfirmasi_hiv_plus_provinsi` TEXT DEFAULT NULL,
    `konfirmasi_hiv_plus_kabkot` TEXT DEFAULT NULL,
    `konfirmasi_hiv_plus_layanan` TEXT DEFAULT NULL,
    `akhir_followup_sblm_masuk_perawatan_meninggal` TINYINT(1) DEFAULT NULL,
    `pendampingan_komunitas` TINYINT(1) DEFAULT NULL,
    `akhir_followup_sblm_masuk_perawatan_dan_arv_meninggal` TINYINT(1) DEFAULT NULL,
    `capaian_t_dan_t_layanan` VARCHAR(10) DEFAULT NULL,
    `capaian_t_dan_t_kabkot` VARCHAR(10) DEFAULT NULL,
    `capaian_t_dan_t_provinsi` VARCHAR(10) DEFAULT NULL,
    `active` tinyint(4) DEFAULT 1,
    `update_at` datetime DEFAULT current_timestamp,
    `tahun_anggaran` year(4) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX(`id_pasien`),
    INDEX(`kabkot`),
    INDEX(`tahun_anggaran`),
    INDEX(`active`)
);

CREATE TABLE `mapping_aids` (
    `id` int(11) NOT NULL auto_increment,
    `kode_desa_aids` VARCHAR(100) DEFAULT NULL,
    `kode_desa_satset` VARCHAR(100) DEFAULT NULL,
    `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX(`kode_desa_aids`)
);